vlm_kwargs:
  min_vram_gb: 17.3
  vlm_id: "${oc.env:DESIGNLORA_MODELS_DIR,/data1/models}/idefics2"
  # vlm_id: HuggingFaceM4/idefics2-8b
  vlm_cls: AutoModelForImageTextToText
  load_in_4bit: False
  torch_dtype: torch.bfloat16
vlm_template:
  image_token: "<image>"
  prefix: "User: {image_token}\n{question}<end_of_utterance>\nAssistant: "
# VLM free-form generation settings
vlm_generate_kwargs:
  do_sample: true
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.05
  min_new_tokens: 8
  max_new_tokens: 96